name: WINDOWS BUILD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: thealphavideo

    - uses: actions/upload-artifact@v2
      with:
        name: alpha-video
        path: thealphavideo/dist/windows
